### ISSUE TITLE
Suggestion for Using Waits and EC instead of sleep

### ISSUE THREAD

**Issue by autumnlewjb** [swaaz/InstaBot#19]
Greetings, I'm a Python and Selenium beginner and I can't let my eye off your code. It's neat and I've learnt plenty. However, I'm curious why did you implement _sleep_ but not _waits_ from Selenium with the help of _expected_conditions_? I always thought that _waits_ in Selenium may save more time as it checks the DOM or the webpage for the element. Is there any downside of using those? Please correct me if I'm wrong here as I'm still a novice to Selenium and automation. And I'm happy to make a pull request if you like to.

**Comment by swaaz** [comment]
@autumnlewjb sleep() is used statically and wait() is used to check DOM or web element to load and then perform the next operation.  I would be really happy if you create a pull request as it is in the development stage.

**Comment by swaaz** [comment]
fixed #20
